/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 model.glb -T --shadows 
Files: model.glb [2.43MB] > model-transformed.glb [737.65KB] (70%)
Author: Lexyc16 (https://sketchfab.com/Lexyc16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-911-930-turbo-1975-de1ffd344c41481892511f7fd332c136
Title: Porsche 911 (930) Turbo 1975
*/

import { useGLTF } from "@react-three/drei";

export function Car() {
  console.log("hi");
  const { nodes, materials } = useGLTF("/models/car/model-transformed.glb");
  console.log(useGLTF("/models/car/model-transformed.glb"));
  return (
    <group dispose={null} castShadow>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial005}
        position={[-1, 1, 0]}
        scale={[0.069, 0.036, 0.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials["Material.013"]}
        position={[-1.093, -1.092, 1.814]}
        scale={[0.069, 0.036, 0.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.093, -1.092, 1.855]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials["Material.003"]}
        position={[-1.093, -1.092, 1.855]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.PaletteMaterial003}
        position={[-1.093, -1.092, 1.855]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials["Material.010"]}
        position={[-1.093, -1.092, 1.855]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.PaletteMaterial004}
        position={[-1.093, -1.092, 1.855]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials.PaletteMaterial005}
        position={[-1.698, -1.315, 1.084]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.261, 0.263, 0.261]}
      />
    </group>
  );
}

useGLTF.preload("/models/car/model-transformed.glb");
